name: Run PowerShell Script

on:
  workflow_dispatch:  # manually trigger
  push:
    branches:
      - main  # activate on commit to the main branch

jobs:
  manage-waf-rules:
    name: manage WAF rules
    runs-on: ubuntu-latest



    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
     
    # pwsh is already available in the ubuntu-latest image
    # - name: Install PowerShell
    #   run: |
    #     if command -v pwsh &> /dev/null; then
    #       echo "PowerShell is already installed."
    #     else
    #       sudo apt-get update
    #       sudo apt-get install -y wget apt-transport-https software-properties-common
    #       wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
    #       sudo dpkg -i packages-microsoft-prod.deb
    #       sudo apt-get update
    #       sudo apt-get install -y powershell
    #     fi

    - name: Install PowerShell
      uses: PSModule/install-powershell@v1
      with:
        Version: latest

    - name: Run a PowerShell script
      shell: pwsh
      run: |
        Write-Host "Using PowerShell $($PSVersionTable.PSVersion)"
    - name: Run PowerShell script
      shell: pwsh
      env:
        WAF_API_KEY: ${{ secrets.WAF_API_KEY }}
        WAF_API_KEY_SECRET: ${{ secrets.WAF_API_KEY_SECRET }}
      run: |
        Write-Host "Running PowerShell script..."
        ./waf-rule-manager.ps1
